import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { Navbar } from "~/components/Navbar";
import EditorComponent from "~/components/Editor";

const Editor: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Pubworld</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-lightBlack">
        <Navbar />
        <div id="mainBody" className="h-full w-full text-white text-opacity-80">
          <EditorComponent />
        </div>
      </main>
    </>
  );
};

export default Editor;
